### ISSUE TITLE
[BUG] Embebbed BND Tool ends with errors but build is sucessfull

### ISSUE THREAD

**Issue by sparsick** [reficio/p2-maven-plugin#241]
The embedded BND tool ends with errors but the plugin doesn't stop, the build is marked as successful and the generated P2 repository is broken.

```xml
[INFO] --- p2-maven-plugin:1.5.0:site (default-cli) @ example-repo ---
.....
[error]  : Exception: java.lang.ArrayIndexOutOfBoundsException
[error]  : Invalid class file module-info.class (java.lang.ArrayIndexOutOfBoundsException)
[error]  : Classes found in the wrong directory: {META-INF/versions/9/org/glassfish/pfl/basic/reflection/Bridge.class=org.glassfish.pfl.basic.reflection.Bridge, META-INF/versions/11/org/glassfish/pfl/basic/reflection/Bridge.class=org.glassfish.pfl.basic.reflection.Bridge}
[info]   [WARN] No source found for com.oracle.weblogic.wlthint3client_14.1.1
[info] Created feature weblogic.feature
[INFO] Command line:
        [/home/sparsick/.sdkman/candidates/java/11.0.6.j9-adpt/bin/java, -jar, /home/sparsick/.m2/repository/org/eclipse/tycho/tycho-bundles-external/1.0.0/eclipse/plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar, -configuration, /tmp/tycho-p2-runtime291946642903149415.tmp/configuration, -nosplash, -application, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, -artifactRepository, file:/home/sparsick/dev/workspace/repo/target/repository, -metadataRepository, file:/home/sparsick/dev/workspace/repo/target/repository, -publishArtifacts, -compress, -consoleLog, -debug, -verbose, -source, /home/sparsick/dev/workspace/repo/target/source]
Configuration location:
    file:/tmp/tycho-p2-runtime291946642903149415.tmp/configuration/
Configuration file:
    file:/tmp/tycho-p2-runtime291946642903149415.tmp/configuration/config.ini loaded
Install location:
    file:/tmp/tycho-p2-runtime291946642903149415.tmp/
Framework located:
    file:/home/sparsick/.m2/repository/org/eclipse/tycho/tycho-bundles-external/1.0.0/eclipse/plugins/org.eclipse.osgi_3.11.2.v20161107-1947.jar
Framework classpath:
    file:/home/sparsick/.m2/repository/org/eclipse/tycho/tycho-bundles-external/1.0.0/eclipse/plugins/org.eclipse.osgi_3.11.2.v20161107-1947.jar
Debug options:
    file:/home/sparsick/dev/workspace/repo/.options not found
Time to load bundles: 220
!SESSION 2021-03-10 20:29:07.796 -----------------------------------------------
eclipse.buildId=unknown
java.fullversion=11.0.6+10
JRE 11 Linux amd64-64-Bit Compressed References 20200116_433 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 104cab2452 based on jdk-11.0.6+10
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher -artifactRepository file:/home/sparsick/dev/workspace/repo/target/repository -metadataRepository file:/home/sparsick/dev/workspace/repo/target/repository -publishArtifacts -compress -verbose -source /home/sparsick/dev/workspace/repo/target/source
Command-line arguments:  -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher -artifactRepository file:/home/sparsick/dev/workspace/repo/target/repository -metadataRepository file:/home/sparsick/dev/workspace/repo/target/repository -publishArtifacts -compress -consoleLog -debug -verbose -source /home/sparsick/dev/workspace/repo/target/source

!ENTRY org.eclipse.tycho.p2.resolver.impl 4 0 2021-03-10 20:29:08.420
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tycho.p2.resolver.impl [53]
  Unresolved requirement: Import-Package: org.eclipse.tycho

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.tycho.p2.maven.repository 4 0 2021-03-10 20:29:08.421
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tycho.p2.maven.repository [54]
  Unresolved requirement: Import-Package: org.eclipse.tycho

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.tycho.p2.tools.impl 4 0 2021-03-10 20:29:08.421
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tycho.p2.tools.impl [55]
  Unresolved requirement: Import-Package: org.eclipse.tycho

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Starting application: 735
Generating metadata for ..
Generation completed with success [0 seconds].
[INFO] Command line:
        [/home/sparsick/.sdkman/candidates/java/11.0.6.j9-adpt/bin/java, -jar, /home/sparsick/.m2/repository/org/eclipse/tycho/tycho-bundles-external/1.0.0/eclipse/plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar, -configuration, /tmp/tycho-p2-runtime8123870047158133810.tmp/configuration, -nosplash, -application, org.eclipse.equinox.p2.publisher.CategoryPublisher, -categoryDefinition, file://home/sparsick/dev/workspace/repo/target/repository/category.xml, -metadataRepository, file://home/sparsick/dev/workspace/repo/target/repository, -consoleLog, -debug, -verbose]
Configuration location:
    file:/tmp/tycho-p2-runtime8123870047158133810.tmp/configuration/
Configuration file:
    file:/tmp/tycho-p2-runtime8123870047158133810.tmp/configuration/config.ini loaded
Install location:
    file:/tmp/tycho-p2-runtime8123870047158133810.tmp/
Framework located:
    file:/home/sparsick/.m2/repository/org/eclipse/tycho/tycho-bundles-external/1.0.0/eclipse/plugins/org.eclipse.osgi_3.11.2.v20161107-1947.jar
Framework classpath:
    file:/home/sparsick/.m2/repository/org/eclipse/tycho/tycho-bundles-external/1.0.0/eclipse/plugins/org.eclipse.osgi_3.11.2.v20161107-1947.jar
Debug options:
    file:/home/sparsick/dev/workspace/repo/target/repository/.options not found
Time to load bundles: 287
!SESSION 2021-03-10 20:29:09.902 -----------------------------------------------
eclipse.buildId=unknown
java.fullversion=11.0.6+10
JRE 11 Linux amd64-64-Bit Compressed References 20200116_433 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 104cab2452 based on jdk-11.0.6+10
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -application org.eclipse.equinox.p2.publisher.CategoryPublisher -categoryDefinition file://home/sparsick/dev/workspace/repo/target/repository/category.xml -metadataRepository file://home/sparsick/dev/workspace/repo/target/repository -verbose
Command-line arguments:  -application org.eclipse.equinox.p2.publisher.CategoryPublisher -categoryDefinition file://home/sparsick/dev/workspace/repo/target/repository/category.xml -metadataRepository file://home/sparsick/dev/workspace/repo/target/repository -consoleLog -debug -verbose

!ENTRY org.eclipse.tycho.p2.resolver.impl 4 0 2021-03-10 20:29:10.691
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tycho.p2.resolver.impl [53]
  Unresolved requirement: Import-Package: org.eclipse.tycho

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.tycho.p2.maven.repository 4 0 2021-03-10 20:29:10.692
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tycho.p2.maven.repository [54]
  Unresolved requirement: Import-Package: org.eclipse.tycho

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.tycho.p2.tools.impl 4 0 2021-03-10 20:29:10.693
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tycho.p2.tools.impl [55]
  Unresolved requirement: Import-Package: org.eclipse.tycho

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Starting application: 970
Generating metadata for ..
Generation completed with success [0 seconds].
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.055 s
[INFO] Finished at: 2021-03-10T20:29:13+01:00
[INFO] ------------------------------------------------------------------------

```

**Comment by sparsick** [comment]
It seems according to an IT-test, that in some case a bnd error doesn't result in an inconsistent P2 repo (see bug18-it).

Idea: introduce a new parameter `ignoringBndError` with default value `true` to be backward compatible.
