### ISSUE TITLE
Issues building a p2 site for particular maven artifact

### ISSUE THREAD

**Issue by loulloudesn** [reficio/p2-maven-plugin#53]
Hi all,

I am having a problem building a p2 site that contains the following artifact: 
<id>org.apache.jclouds.labs:openstack-neutron:1.8.0</id>

Any insights would be very valuable.

Regards,
Nicholas

------ POM.XML -------

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.jclouds</groupId>
    <artifactId>p2-site</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

```
<build>
    <plugins>
        <plugin>
            <groupId>org.reficio</groupId>
            <artifactId>p2-maven-plugin</artifactId>
            <version>1.1.1-SNAPSHOT</version>
            <executions>
                <execution>
                    <id>default-cli</id>
                </execution>
            </executions>
            <configuration>
                <artifacts>
                    <artifact>
                        <id>org.apache.jclouds.labs:openstack-neutron:1.7.3</id>
                    </artifact>
                </artifacts>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.mortbay.jetty</groupId>
            <artifactId>jetty-maven-plugin</artifactId>
            <version>8.1.5.v20120716</version>
            <configuration>
                <scanIntervalSeconds>10</scanIntervalSeconds>
                <webAppSourceDirectory>${basedir}/target/repository/</webAppSourceDirectory>
                <webApp>
                    <contextPath>/site</contextPath>
                </webApp>
            </configuration>
        </plugin>
    </plugins>
</build>


<pluginRepositories>
    <pluginRepository>
        <id>reficio</id>
        <url>http://repo.reficio.org/maven/</url>
    </pluginRepository>
</pluginRepositories>
```

</project>

---

------------------------ Stack trace:- ----------------------------------

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building p2-site 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- p2-maven-plugin:1.1.1-SNAPSHOT:site (default-cli) @ p2-site ---
[info] Resolving artifact=[org.apache.jclouds.labs:openstack-neutron:1.8.0] transitive=[false] source=[false]
[info]   [JAR] openstack-neutron-1.8.0.jar
[info] Executing Bundler:
[info]   [SKIP] openstack-neutron-1.8.0.jar
[INFO] Command line:
    /bin/sh -c cd /home/nickl/workspace/openstack-neutron && /usr/lib/jvm/java-6-openjdk/jre/bin/java -jar /home/nickl/.m2/repository/org/eclipse/tycho/tycho-bundles-external/0.18.1/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar -configuration /tmp/tycho-p2-runtime5358553969148673763.tmp/configuration -nosplash -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher -artifactRepository file:/home/nickl/workspace/openstack-neutron/target/repository -metadataRepository file:/home/nickl/workspace/openstack-neutron/target/repository -publishArtifacts -compress -source /home/nickl/workspace/openstack-neutron/target/source
Generating metadata for ..
Status ERROR: org.eclipse.equinox.p2.artifact.repository code=0 invalid range "${jclouds.version}": invalid version "${jclouds.version}": non-numeric "${jclouds" java.lang.IllegalArgumentException: invalid range "${jclouds.version}": invalid version "${jclouds.version}": non-numeric "${jclouds"

Product publishing ended with the following exception:
java.lang.IllegalArgumentException: invalid range "${jclouds.version}": invalid version "${jclouds.version}": non-numeric "${jclouds"
    at org.osgi.framework.VersionRange.parseVersion(VersionRange.java:196)
    at org.osgi.framework.VersionRange.<init>(VersionRange.java:150)
    at org.eclipse.osgi.service.resolver.VersionRange.<init>(VersionRange.java:68)
    at org.eclipse.osgi.internal.resolver.StateBuilder.getVersionRange(StateBuilder.java:805)
    at org.eclipse.osgi.internal.resolver.StateBuilder.addImportPackages(StateBuilder.java:293)
    at org.eclipse.osgi.internal.resolver.StateBuilder.createImportPackages(StateBuilder.java:272)
    at org.eclipse.osgi.internal.resolver.StateBuilder.createBundleDescription(StateBuilder.java:117)
    at org.eclipse.osgi.internal.resolver.StateObjectFactoryImpl.createBundleDescription(StateObjectFactoryImpl.java:33)
    at org.eclipse.equinox.p2.publisher.eclipse.BundlesAction.createBundleDescription(BundlesAction.java:541)
    at org.eclipse.equinox.p2.publisher.eclipse.BundlesAction.createBundleDescription(BundlesAction.java:577)
    at org.eclipse.equinox.p2.publisher.eclipse.BundlesAction.getBundleDescriptions(BundlesAction.java:891)
    at org.eclipse.equinox.p2.publisher.eclipse.BundlesAction.perform(BundlesAction.java:711)
    at org.eclipse.equinox.p2.publisher.Publisher$ArtifactProcess.run(Publisher.java:207)
    at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.executeBatch(SimpleArtifactRepository.java:1344)
    at org.eclipse.equinox.p2.publisher.Publisher.publish(Publisher.java:231)
    at org.eclipse.equinox.p2.publisher.AbstractPublisherApplication.run(AbstractPublisherApplication.java:283)
    at org.eclipse.equinox.p2.publisher.AbstractPublisherApplication.run(AbstractPublisherApplication.java:253)
    at org.eclipse.equinox.p2.publisher.AbstractPublisherApplication.start(AbstractPublisherApplication.java:317)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.equinox.internal.app.AnyThreadAppLauncher.run(AnyThreadAppLauncher.java:26)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.IllegalArgumentException: invalid version "${jclouds.version}": non-numeric "${jclouds"
    at org.osgi.framework.Version.parseInt(Version.java:170)
    at org.osgi.framework.Version.<init>(Version.java:126)
    at org.osgi.framework.Version.parseVersion(Version.java:233)
    at org.osgi.framework.VersionRange.parseVersion(VersionRange.java:194)
    ... 20 more
Caused by: java.lang.NumberFormatException: For input string: "${jclouds"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:470)
    at java.lang.Integer.parseInt(Integer.java:514)
    at org.osgi.framework.Version.parseInt(Version.java:168)
    ... 23 more

Product publisher application was executed with the following arguments:
-artifactRepository
file:/home/nickl/workspace/openstack-neutron/target/repository
-metadataRepository
file:/home/nickl/workspace/openstack-neutron/target/repository
-publishArtifacts
-compress
-source
/home/nickl/workspace/openstack-neutron/target/source
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.796 s
[INFO] Finished at: 2014-09-17T11:51:45+03:00
[INFO] Final Memory: 14M/456M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.reficio:p2-maven-plugin:1.1.1-SNAPSHOT:site (default-cli) on project p2-site: Execution default-cli of goal org.reficio:p2-maven-plugin:1.1.1-SNAPSHOT:site failed: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo: P2 publisher return code was 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by bmarwell** [comment]
@loulloudesn 
`jclouds.version` is a property that needs to be defined. Did you post your full `pom.xml`?

Also, please make sure to use more code tags for readability.
