### ISSUE TITLE
ArrayIndexOutOfBoundsException for java8 bundles

### ISSUE THREAD

**Issue by nevries** [reficio/p2-maven-plugin#81]
For some bundles that are most likely compiled with/for java 8, the process fails. I tested org.controlsfx:controlsfx:8.40.9 and org.jfxtras:jfxtras-controls:8.0-r3. Please find the stacktrace below. The problem results in bundles with missing export-package entries, rendering them useless.

[info]   [EXEC] controlsfx-8.40.9.jar
java.lang.ArrayIndexOutOfBoundsException: 18
    at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:448)
    at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:369)
    at aQute.lib.osgi.Clazz.parseClassFileWithCollector(Clazz.java:359)
    at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:349)
    at aQute.lib.osgi.Analyzer.analyzeJar(Analyzer.java:1725)
    at aQute.lib.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:1595)
    at aQute.lib.osgi.Analyzer.analyze(Analyzer.java:124)
    at aQute.lib.osgi.Analyzer.calcManifest(Analyzer.java:301)
    at org.reficio.p2.bundler.impl.AquteBundler.handleVanillaJarWrap(AquteBundler.java:94)
    at org.reficio.p2.bundler.impl.AquteBundler.doWrap(AquteBundler.java:71)
    at org.reficio.p2.bundler.impl.AquteBundler.execute(AquteBundler.java:60)
    at org.reficio.p2.P2Mojo.bundleArtifact(P2Mojo.java:363)
    at org.reficio.p2.P2Mojo.processRootArtifacts(P2Mojo.java:261)
    at org.reficio.p2.P2Mojo.processArtifacts(P2Mojo.java:251)
    at org.reficio.p2.P2Mojo.execute(P2Mojo.java:208)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[...]
[warn]  : Superfluous export-package instructions: [org.controlsfx, impl.org.controlsfx.control, impl, impl.org, org]
[error]  : Exception: 18
[error]  : Invalid class file: impl/org/controlsfx/behavior/SnapshotViewBehavior.class
[...]

Tried with 1.2.0-SNAPSHOT.

**Comment by tJeyhun** [comment]
Same happens with RitchTextFX bundle (JDK8) (org.fxmisc.richtext:richtextfx:0.6.6)

**Comment by schulzp** [comment]
This should be fixed when updating the dependency on the [maven-bundle-plugin](https://issues.apache.org/jira/browse/FELIX-4005). Overriding the dependency in the pom using `p2-maven-plugin` does not work, however.

**Comment by tJeyhun** [comment]
Can not be used on any new java8 bundles. It is really frustrating! Cause is old bnd tool. Please update!!

**Comment by Venorcis** [comment]
Any ETA on this?

**Comment by tombujok** [comment]
Has been upgraded to 3.3.0 and merged. 1.2.0 released yesterday. Should be in maven central today
