### ISSUE TITLE
POM dependency prevent site generation

### ISSUE THREAD

**Issue by maggu2810** [reficio/p2-maven-plugin#93]
If there is an artifact that contains e.g. a pom as a transitive dependency, this will break the site generation.

```text
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.753 s
[INFO] Finished at: 2016-03-08T18:50:16+01:00
[INFO] Final Memory: 18M/619M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.reficio:p2-maven-plugin:1.2.0-SNAPSHOT:site (default-cli) on project example-p2-site: Execution default-cli of goal org.reficio:p2-maven-plugin:1.2.0-SNAPSHOT:site failed: java.lang.RuntimeException: The JAR/ZIP file (.../example-1.0.0-SNAPSHOT.pom) seems corrupted, error: error in opening zip file -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.reficio:p2-maven-plugin:1.2.0-SNAPSHOT:site (default-cli) on project example-p2-site: Execution default-cli of goal org.reficio:p2-maven-plugin:1.2.0-SNAPSHOT:site failed: java.lang.RuntimeException: The JAR/ZIP file (.../example-1.0.0-SNAPSHOT.pom) seems corrupted, error: error in opening zip file
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.reficio:p2-maven-plugin:1.2.0-SNAPSHOT:site failed: java.lang.RuntimeException: The JAR/ZIP file (.../example-1.0.0-SNAPSHOT.pom) seems corrupted, error: error in opening zip file
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: The JAR/ZIP file (.../example-1.0.0-SNAPSHOT.pom) seems corrupted, error: error in opening zip file
	at org.reficio.p2.P2Mojo.execute(P2Mojo.java:215)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.RuntimeException: The JAR/ZIP file (.../example-1.0.0-SNAPSHOT.pom) seems corrupted, error: error in opening zip file
	at org.reficio.p2.utils.BundleUtils.isBundle(BundleUtils.java:80)
	at org.reficio.p2.P2Validator.validateArtifactConfig(P2Validator.java:46)
	at org.reficio.p2.P2Validator.validateBundleRequest(P2Validator.java:35)
	at org.reficio.p2.P2Mojo.bundleArtifact(P2Mojo.java:359)
	at org.reficio.p2.P2Mojo.processTransitiveArtifacts(P2Mojo.java:280)
	at org.reficio.p2.P2Mojo.processArtifacts(P2Mojo.java:252)
	at org.reficio.p2.P2Mojo.execute(P2Mojo.java:208)
	... 22 more
Caused by: java.util.zip.ZipException: The JAR/ZIP file (.../example-1.0.0-SNAPSHOT.pom) seems corrupted, error: error in opening zip file
	at aQute.lib.osgi.ZipResource.build(ZipResource.java:59)
	at aQute.lib.osgi.ZipResource.build(ZipResource.java:33)
	at aQute.lib.osgi.Jar.<init>(Jar.java:40)
	at aQute.lib.osgi.Jar.<init>(Jar.java:61)
	at org.reficio.p2.utils.BundleUtils.isBundle(BundleUtils.java:77)
	... 28 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

What do you think is the best way to handle such non-JAR/-ZIP stuff in the resolved artifacts?

I could use something similar to this one, but I don't know if this is the correct way to handle such errors.

```diff
diff --git a/src/main/java/org/reficio/p2/P2Mojo.java b/src/main/java/org/reficio/p2/P2Mojo.java
index 9fa3291..8c06f40 100644
--- a/src/main/java/org/reficio/p2/P2Mojo.java
+++ b/src/main/java/org/reficio/p2/P2Mojo.java
@@ -276,8 +275,13 @@ public class P2Mojo extends AbstractMojo implements Contextualizable {
         for (P2Artifact p2Artifact : artifacts) {
             for (ResolvedArtifact resolvedArtifact : resolvedArtifacts.get(p2Artifact)) {
                 if (!resolvedArtifact.isRoot()) {
-                    if (bundledArtifacts.add(resolvedArtifact.getArtifact())) {
-                        bundleArtifact(p2Artifact, resolvedArtifact);
+                    if (!bundledArtifacts.contains(resolvedArtifact.getArtifact())) {
+                        try {
+                            bundleArtifact(p2Artifact, resolvedArtifact);
+                            bundledArtifacts.add(resolvedArtifact.getArtifact());
+                        } catch (final RuntimeException ex) {
+                            log.warn(String.format("Skip artifact=[%s]: %s", p2Artifact.getId(), ex.getMessage()));
+                        }
                     } else {
                         log.debug(String.format("Not bundling transitive dependency since it has already been bundled [%s]", resolvedArtifact.getArtifact()));
                     }
```

**Comment by tombujok** [comment]
Fixed. Thx to @maggu2810
